### ISSUE TITLE
Is this still up to date with the current version of the API?

### ISSUE THREAD

**Issue by pwr22** [leejo/business-mondo#8]
> it implements all of the functionality currently found in the service's API documentation: https://monzo.com/docs

Is this still true as of today?

**Comment by leejo** [comment]
Possibly not having taken a quick look at the docs. It should be trivial to add the missing endpoints however. I'll see if I can look at this next week, alternatively I'd be happy with a PR if you want to look at it. Ta!

**Comment by pwr22** [comment]
I'll try to take a look 👍. Not sure if much has changed with the coming of the current account either 🤷‍♂️

**Comment by devi4nt** [comment]
Hello gents - I’ve been having a play with getting support for the pots end point.

Will let you know how I get on, perhaps you’ll get a PR soon if all goes well.

**Comment by leejo** [comment]
I'm about to push the latest version, with additions from @devi4nt and documentation for pagination. With that I believe the dist is up to date with the current docs, although have not tested any of the AISP Access stuff.
